# -*- coding: utf-8 -*-
"""tarea_Extraccion _Datos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H6CIkDISe1kCwI07Y_9-jQT0jnntsY_S
"""

#importamos librerias requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io

#cargar archivo csv desde equipo
from google.colab import files
files.upload()

#convertir en dataframe
df= pd.read_csv("CountryTable.csv")
df

#imprimimos las primeras filas o registros del dataframe 
df.head(10)

#imprimimos las primeras filas o registros del dataframe 
df.head(8)

"""*FILTROS BASICOS PARA VARIABLES CUALITATIVAS*"""

#filtro por objeto
filtro1=df[df["Entidad_Federativa"] == "Puebla"]
filtro1

#filtro 
#filtro2= df.iloc[300:302,: ]
filtro2=df.iloc[ [1000,2000,3000],:]#filas no consecutivas
filtro2b=df.iloc[ 1000:2000, : ]#filas consecutivas
filtro2

#FILTRO NÚMERO 3
#Ejemplo 1:
filtro_columna=df.iloc[ 40:45 , 1:6]
 
filtro_columna

#FILTRO NÚMERO 3
#Ejemplo 2:
filtro_columna_2=df.iloc[ 55:70 , [1,6,7]]
 
filtro_columna_2

#filtro de filas vs columnas
#FILTRO #4
#Ejemplo 1:
#Paso 1
from google.colab import files
uploaded=files.upload() 
df = pd.read_csv(io.BytesIO(uploaded["CountryTable.csv"]), index_col=2)
df

#Ejemplo #1
#Paso 2
filtro4=df.loc[["Africa","Europe"],["population"]]
filtro4

#Filtro #4 
#Ejemplo #2
#Paso 1
from google.colab import files
uploaded=files.upload() 
df = pd.read_csv(io.BytesIO(uploaded["CountryTable.csv"]), index_col=3)
df

#Ejemplo #2
#Paso 2
filtro4_2=df.loc[["South America","Western Europe"],["life_expectancy"]]
filtro4_2

#filtro por cabecera
filtro5=df.head(11)#Aqui estoy poniendo las primera 11 columnas 
filtro5

"""**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

"""

#Filtro por comparacion
filtro6=df[df["Periodo"] >= 2010]
filtro6

"""**Filtros basicos con conectroes logicos**"""

#filtro y
filtro7=df[(df)["Periodo"]>2015 & (df["Sexo"]== "Hombres")]
filtro7

#filtro o
filtro8=df[(df["Periodo"] > 2006) | (df["Sexo"]== "Mujeres")]
filtro8

#filtro not
filtro9=df[~(df["Periodo"] >=2006) & ~ (df["Sexo"] == "Mujeres")]
filtro9

#convertir archivo filtrado a CSV
filtro9.to_csv("Entregable.csv")

filtro_columna.to_csv("Filtro3(ejemplo1).csv")

from google.colab import files

files.download("Filtro3(ejemplo1).csv")

filtro_columna_2.to_csv("Filtro3(ejemplo2).csv")

from google.colab import files

files.download("Filtro3(ejemplo2).csv")

filtro4.to_csv("Filtro4(ejemplo1).csv")

from google.colab import files

files.download("Filtro4(ejemplo1).csv")

filtro4_2.to_csv("Filtro4(ejemplo2).csv")

from google.colab import files

files.download("Filtro4(ejemplo2).csv")



#descargar archivo filtrado csv
from google.colab import files

files.download("Entregable.csv")